[project]
name = "suvinil-colors"
version = "0.1.0"
requires-python = ">=3.10,<3.14"
dependencies = [
    "streamlit>=1.30.0",
    "pillow>=10.0.0"
]

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.14"