[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "olho-da-mel"
version = "1.0.0"
description = "Encontrador de cores similares Suvinil"
requires-python = ">=3.10,<3.11"

[tool.setuptools]
packages = ["."] 